name: Deploy to Github Pages
on:
    push:
        branches:
            - develop

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Create Node Environment
          uses: actions/setup-node@v4
          with: 
            node-version: 16.x
        - name: Install Packages and Build Application
          run: |
            npm ci
            npm run build
        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v3
        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ./dist/
            destination: ./_site
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
      
    deploy:
      name: Deploy Application

      # Add a dependency to the build job
      needs: build

      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action

# name: Build and Deploy Vue Application to Github Pages
# on: 
#     push:
#         branch:
#             -develop
# jobs:
#   build_deploy_vue:
#     runs-on: ubuntu-latest
#     name: Build and Deploy Vue
#     steps:
#     - uses: actions/checkout@v2
#     - id: Build-Deploy-Vue
#       uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
#       with:
#         username: 'BhumikKalola21'
#         reponame: 'sample-project'
#         token: ${{ secrets.GITHUB_TOKEN }} 